version: 0.1
os: linux
files:
 - source: .
   destination: /home/ubuntu/app
hooks:
  AfterInstall:
   - location: scripts/install.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/deploy.sh
     timeout: 300
     runas: root